In [ ]:
! pip install pymorphy2

Collecting pymorphy2
  Downloading https://files.pythonhosted.org/packages/07/57/b2ff2fae3376d4f3c697b9886b64a54b476e1a332c67eee9f88e7f1ae8c9/pymorphy2-0.9.1-py3-none-any.whl (55kB)
     |████████████████████████████████| 61kB 4.2MB/s
Requirement already satisfied: docopt>=0.6 in /usr/local/lib/python3.6/dist-packages (from pymorphy2) (0.6.2)
Collecting pymorphy2-dicts-ru<3.0,>=2.4
  Downloading https://files.pythonhosted.org/packages/3a/79/bea0021eeb7eeefde22ef9e96badf174068a2dd20264b9a378f2be1cdd9e/pymorphy2_dicts_ru-2.4.417127.4579844-py2.py3-none-any.whl (8.2MB)
     |████████████████████████████████| 8.2MB 9.7MB/s
Collecting dawg-python>=0.7.1
  Downloading https://files.pythonhosted.org/packages/6a/84/ff1ce2071d4c650ec85745766c0047ccc3b5036f1d03559fd46bb38b5eeb/DAWG_Python-0.7.2-py2.py3-none-any.whl
Installing collected packages: pymorphy2-dicts-ru, dawg-python, pymorphy2
Successfully installed dawg-python-0.7.2 pymorphy2-0.9.1 pymorphy2-dicts-ru-2.4.417127.4579844

In [44]:
import nltk
from nltk.tokenize import word_tokenize

from pymorphy2 import MorphAnalyzer
morph = MorphAnalyzer()

from collections import Counter
import collections

import nltk
nltk.download('punkt')

from tqdm import tqdm

import numpy as np
import matplotlib.pyplot as plt

import pandas as pd

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [5]:
def pos_frequency(file):
    with open(file, 'r', encoding='utf-8') as t:
        text = t.read()
        tokens = word_tokenize(text)
        words = [w for w in tokens if w.isalpha()]

        lemmas = []

        for i in tqdm(words):
            analise = morph.parse(i)
            lemmas.append(analise)
            
        forms_from_text = []
        for lemma in lemmas:
            one = lemma[0]
            form = [one.normal_form, one.tag.POS]
            forms_from_text.append(form)

        pos = []
        freq = []

        counter_of_forms = collections.Counter()
        allf = 0
        for i in forms_from_text:
            allf = allf + 1
            form = i[1]
            counter_of_forms[form] += 1

        return counter_of_forms

In [6]:
a_Litvinovy = pos_frequency('/content/drive/MyDrive/Colab Notebooks/Курсовая/author_Litvinovy')

100%|██████████| 2459154/2459154 [11:23<00:00, 3600.13it/s]

In [8]:
a_Marinina = pos_frequency('/content/drive/MyDrive/Colab Notebooks/Курсовая/author_Marinina')
a_Polyakova = pos_frequency('/content/drive/MyDrive/Colab Notebooks/Курсовая/author_Polyakova')
a_Ustinova = pos_frequency('/content/drive/MyDrive/Colab Notebooks/Курсовая/author_Ustinova')

100%|██████████| 3141686/3141686 [14:21<00:00, 3647.19it/s]
100%|██████████| 3199281/3199281 [13:46<00:00, 3872.86it/s]
100%|██████████| 2183784/2183784 [09:47<00:00, 3720.13it/s]

In [9]:
d_Litvinovy = pos_frequency('/content/drive/MyDrive/Colab Notebooks/Курсовая/dialog_Litvinovy')
d_Marinina = pos_frequency('/content/drive/MyDrive/Colab Notebooks/Курсовая/dialog_Marinina')
d_Ustinova = pos_frequency('/content/drive/MyDrive/Colab Notebooks/Курсовая/dialog_Ustinova')
d_Polyakova = pos_frequency('/content/drive/MyDrive/Colab Notebooks/Курсовая/dialog_Polyakova')

100%|██████████| 1025725/1025725 [04:07<00:00, 4140.80it/s]
100%|██████████| 1581543/1581543 [06:31<00:00, 4040.96it/s]
100%|██████████| 1051378/1051378 [04:27<00:00, 3928.33it/s]
100%|██████████| 1530105/1530105 [06:13<00:00, 4094.43it/s]

In [80]:
df_aL = pd.DataFrame(a_Litvinovy.values(), a_Litvinovy.keys())
print('Литвиновы: авторская речь')
df_aL.to_csv('Litvinovy_author.csv')
df_aL

Литвиновы: авторская речь

           0
NOUN  671993
PREP  281985
ADJF  266300
VERB  339921
PRCL  132602
NPRO  160879
CONJ  254673
ADVB  184629
INFN   69072
PRTF   20878
NUMR   19726
ADJS   14925
PRED   10471
PRTS    6107
COMP   10414
GRND    9835
INTJ    2482

In [81]:
df_dL = pd.DataFrame(d_Litvinovy.values(), d_Litvinovy.keys())
print('Литвиновы: прямая речь')
df_dL.to_csv('Litvinovy_dialog.csv')
df_dL

Литвиновы: прямая речь

           0
NOUN  233123
ADJF   85451
VERB  167322
NPRO  116065
ADVB   79131
PRCL   74402
ADJS    8186
PREP   95340
CONJ  104504
INFN   29036
COMP    4411
INTJ    3148
PRTF    3158
NUMR    7661
PRED    8309
GRND    2602
PRTS    2279

In [82]:
df_aM = pd.DataFrame(a_Marinina.values(), a_Marinina.keys())
print('Маринина: авторская речь')
df_aM.to_csv('Marinina_author.csv')
df_aM

Маринина: авторская речь

           0
NOUN  777054
CONJ  361895
PREP  329526
ADJF  317092
NPRO  246124
ADVB  233016
INFN  118962
VERB  413155
PRTF   26996
PRCL  204313
ADJS   22681
GRND   20091
COMP   13946
PRED   23717
NUMR   21044
PRTS    9339
INTJ    2167

In [83]:
df_dM = pd.DataFrame(d_Marinina.values(), d_Marinina.keys())
print('Маринина: прямая речь')
df_dM.to_csv('Marinina_dialog.csv')
df_dM

Маринина: прямая речь

           0
ADVB  119863
NOUN  322226
VERB  239992
PREP  141774
NPRO  190312
GRND    5490
PRTF    4858
ADJF  131785
CONJ  182670
INFN   61048
PRCL  126835
PRTS    4419
ADJS   14419
INTJ    2283
PRED   15894
COMP    7397
NUMR   10113

In [84]:
df_aU = pd.DataFrame(a_Ustinova.values(), a_Ustinova.keys())
print('Устинова: авторская речь')
df_aU.to_csv('Ustinova_author.csv')
df_aU

Устинова: авторская речь

           0
NOUN  530622
ADJF  203561
VERB  330370
NPRO  185444
INFN   64439
CONJ  253970
PRCL  133321
PREP  223633
ADVB  170121
ADJS   15495
COMP    8752
PRTS    4919
PRED   12776
GRND   15940
NUMR    9066
PRTF   19059
INTJ    1517

In [85]:
df_dU = pd.DataFrame(d_Ustinova.values(), d_Ustinova.keys())
print('Устинова: прямая речь')
df_dU.to_csv('Ustinova_dialog.csv')
df_dU

Устинова: прямая речь

           0
INFN   29823
PRCL   84937
VERB  177727
ADVB   82406
PREP   89626
NPRO  134789
NOUN  224332
ADJF   72053
PRED   10254
NUMR    4425
CONJ  115646
PRTF    3106
GRND    5810
ADJS    7477
COMP    4309
PRTS    1840
INTJ    2393

In [86]:
df_aP = pd.DataFrame(a_Polyakova.values(), a_Polyakova.keys())
print('Полякова: авторская речь')
df_aP.to_csv('Polyakova_author.csv')
df_aP

Полякова: авторская речь

           0
PREP  348545
NOUN  719954
ADJF  238102
VERB  533880
NPRO  361207
CONJ  334230
PRCL  183587
PRTF   13131
ADVB  237877
ADJS   22115
INFN  104877
COMP   14010
GRND   41935
INTJ    4200
NUMR   17742
PRTS    7635
PRED   15656

In [87]:
df_dP = pd.DataFrame(d_Polyakova.values(), d_Polyakova.keys())
print('Полякова: прямая речь')
df_dP.to_csv('Polyakova_dialog.csv')
df_dP

Полякова: прямая речь

           0
ADVB  111706
NPRO  208348
NOUN  306637
VERB  269939
CONJ  158501
PREP  145857
GRND   13274
ADJF  104267
ADJS   13099
INFN   53196
PRTF    3070
PRCL  109631
NUMR    6692
INTJ    3625
PRED   11476
PRTS    3186
COMP    7180